openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.2
servers:
  - url: https://private.movie.xc-demo.com/
    description: Optional server description, e.g. Main (production) server
  - url: http://express.mylab.local
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /:
    get:
      summary: Return request ip address.
      description: for demo.
      responses:
        '200':    # status code
          description: A string of request ip address
          content:
            application/json:
              schema: 
                type: string
                items: 
                  type: string
  /headers:
    get:
      summary: Returns a list of your request headers.
      description: for demo.
      responses:
        '200':    # status code
          description: A JSON array of user request headers
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string                
  /compare:
    post:
      summary: compare between 2 number from request body.
      description: send 2 number in request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num1:
                  type: integer
                num2:
                  type: integer
      responses:
        '200':    # status code
          description: A JSON array of user request headers
          content:
            application/json:
              schema: 
                type: string
                items: 
                  type: string